kind: pipeline
type: docker
name: Portfolio

trigger:
  event:
    - push

steps:
  - name: docker-build-and-push
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      context: .
      registry: hub.codefirst.iut.uca.fr
      repo: hub.codefirst.iut.uca.fr/noan.randon/portfolio-noan
      username:
        from_secret: SECRET_REGISTRY_USERNAME
      password:
        from_secret: SECRET_REGISTRY_PASSWORD
    depends_on: [ app-build ]